# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule/scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from capsule import common_pb2 as capsule_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule/scheduler.proto',
  package='capsule',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63\x61psule/scheduler.proto\x12\x07\x63\x61psule\x1a\x14\x63\x61psule/common.proto2\xd5\x01\n\tScheduler\x12\'\n\x07SaveUrl\x12\x0c.capsule.Url\x1a\x0e.capsule.Empty\x12\x34\n\rListSnapshots\x12\x0c.capsule.Url\x1a\x15.capsule.SnapshotList\x12\x33\n\x0eRegisterWorker\x12\x11.capsule.Endpoint\x1a\x0e.capsule.Empty\x12\x34\n\x0fRegisterStorage\x12\x11.capsule.Endpoint\x1a\x0e.capsule.Emptyb\x06proto3'
  ,
  dependencies=[capsule_dot_common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='capsule.Scheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=59,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveUrl',
    full_name='capsule.Scheduler.SaveUrl',
    index=0,
    containing_service=None,
    input_type=capsule_dot_common__pb2._URL,
    output_type=capsule_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListSnapshots',
    full_name='capsule.Scheduler.ListSnapshots',
    index=1,
    containing_service=None,
    input_type=capsule_dot_common__pb2._URL,
    output_type=capsule_dot_common__pb2._SNAPSHOTLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterWorker',
    full_name='capsule.Scheduler.RegisterWorker',
    index=2,
    containing_service=None,
    input_type=capsule_dot_common__pb2._ENDPOINT,
    output_type=capsule_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterStorage',
    full_name='capsule.Scheduler.RegisterStorage',
    index=3,
    containing_service=None,
    input_type=capsule_dot_common__pb2._ENDPOINT,
    output_type=capsule_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
