# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from capsule import common_pb2 as capsule_dot_common__pb2


class SchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveUrl = channel.unary_unary(
                '/capsule.Scheduler/SaveUrl',
                request_serializer=capsule_dot_common__pb2.Url.SerializeToString,
                response_deserializer=capsule_dot_common__pb2.Empty.FromString,
                )
        self.ListSnapshots = channel.unary_unary(
                '/capsule.Scheduler/ListSnapshots',
                request_serializer=capsule_dot_common__pb2.Url.SerializeToString,
                response_deserializer=capsule_dot_common__pb2.SnapshotList.FromString,
                )
        self.RegisterWorker = channel.unary_unary(
                '/capsule.Scheduler/RegisterWorker',
                request_serializer=capsule_dot_common__pb2.Endpoint.SerializeToString,
                response_deserializer=capsule_dot_common__pb2.Empty.FromString,
                )
        self.RegisterStorage = channel.unary_unary(
                '/capsule.Scheduler/RegisterStorage',
                request_serializer=capsule_dot_common__pb2.Endpoint.SerializeToString,
                response_deserializer=capsule_dot_common__pb2.Empty.FromString,
                )


class SchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveUrl,
                    request_deserializer=capsule_dot_common__pb2.Url.FromString,
                    response_serializer=capsule_dot_common__pb2.Empty.SerializeToString,
            ),
            'ListSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSnapshots,
                    request_deserializer=capsule_dot_common__pb2.Url.FromString,
                    response_serializer=capsule_dot_common__pb2.SnapshotList.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=capsule_dot_common__pb2.Endpoint.FromString,
                    response_serializer=capsule_dot_common__pb2.Empty.SerializeToString,
            ),
            'RegisterStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterStorage,
                    request_deserializer=capsule_dot_common__pb2.Endpoint.FromString,
                    response_serializer=capsule_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'capsule.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/capsule.Scheduler/SaveUrl',
            capsule_dot_common__pb2.Url.SerializeToString,
            capsule_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/capsule.Scheduler/ListSnapshots',
            capsule_dot_common__pb2.Url.SerializeToString,
            capsule_dot_common__pb2.SnapshotList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/capsule.Scheduler/RegisterWorker',
            capsule_dot_common__pb2.Endpoint.SerializeToString,
            capsule_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/capsule.Scheduler/RegisterStorage',
            capsule_dot_common__pb2.Endpoint.SerializeToString,
            capsule_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
