# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule/storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from capsule import common_pb2 as capsule_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule/storage.proto',
  package='capsule',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63\x61psule/storage.proto\x12\x07\x63\x61psule\x1a\x14\x63\x61psule/common.proto2n\n\x07Storage\x12\x30\n\x0cStoreContent\x12\x10.capsule.Content\x1a\x0e.capsule.Empty\x12\x31\n\nGetContent\x12\x11.capsule.Snapshot\x1a\x10.capsule.Contentb\x06proto3'
  ,
  dependencies=[capsule_dot_common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STORAGE = _descriptor.ServiceDescriptor(
  name='Storage',
  full_name='capsule.Storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=56,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='StoreContent',
    full_name='capsule.Storage.StoreContent',
    index=0,
    containing_service=None,
    input_type=capsule_dot_common__pb2._CONTENT,
    output_type=capsule_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetContent',
    full_name='capsule.Storage.GetContent',
    index=1,
    containing_service=None,
    input_type=capsule_dot_common__pb2._SNAPSHOT,
    output_type=capsule_dot_common__pb2._CONTENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['Storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
