# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule/worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from capsule import common_pb2 as capsule_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule/worker.proto',
  package='capsule',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63\x61psule/worker.proto\x12\x07\x63\x61psule\x1a\x14\x63\x61psule/common.proto24\n\x06Worker\x12*\n\x08\x43rawlUrl\x12\x0c.capsule.Url\x1a\x10.capsule.Contentb\x06proto3'
  ,
  dependencies=[capsule_dot_common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='capsule.Worker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=55,
  serialized_end=107,
  methods=[
  _descriptor.MethodDescriptor(
    name='CrawlUrl',
    full_name='capsule.Worker.CrawlUrl',
    index=0,
    containing_service=None,
    input_type=capsule_dot_common__pb2._URL,
    output_type=capsule_dot_common__pb2._CONTENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
