# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule/storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from capsule import common_pb2 as capsule_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule/storage.proto',
  package='capsule',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63\x61psule/storage.proto\x12\x07\x63\x61psule\x1a\x14\x63\x61psule/common.proto\")\n\x0cStoreRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x19\n\nStorageKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\x1a\n\nStoredData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32x\n\x07Storage\x12\x35\n\x0cStoreContent\x12\x15.capsule.StoreRequest\x1a\x0e.capsule.Empty\x12\x36\n\nGetContent\x12\x13.capsule.StorageKey\x1a\x13.capsule.StoredDatab\x06proto3'
  ,
  dependencies=[capsule_dot_common__pb2.DESCRIPTOR,])




_STOREREQUEST = _descriptor.Descriptor(
  name='StoreRequest',
  full_name='capsule.StoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='capsule.StoreRequest.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='capsule.StoreRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=97,
)


_STORAGEKEY = _descriptor.Descriptor(
  name='StorageKey',
  full_name='capsule.StorageKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='capsule.StorageKey.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=124,
)


_STOREDDATA = _descriptor.Descriptor(
  name='StoredData',
  full_name='capsule.StoredData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='capsule.StoredData.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['StoreRequest'] = _STOREREQUEST
DESCRIPTOR.message_types_by_name['StorageKey'] = _STORAGEKEY
DESCRIPTOR.message_types_by_name['StoredData'] = _STOREDDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StoreRequest = _reflection.GeneratedProtocolMessageType('StoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREREQUEST,
  '__module__' : 'capsule.storage_pb2'
  # @@protoc_insertion_point(class_scope:capsule.StoreRequest)
  })
_sym_db.RegisterMessage(StoreRequest)

StorageKey = _reflection.GeneratedProtocolMessageType('StorageKey', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEKEY,
  '__module__' : 'capsule.storage_pb2'
  # @@protoc_insertion_point(class_scope:capsule.StorageKey)
  })
_sym_db.RegisterMessage(StorageKey)

StoredData = _reflection.GeneratedProtocolMessageType('StoredData', (_message.Message,), {
  'DESCRIPTOR' : _STOREDDATA,
  '__module__' : 'capsule.storage_pb2'
  # @@protoc_insertion_point(class_scope:capsule.StoredData)
  })
_sym_db.RegisterMessage(StoredData)



_STORAGE = _descriptor.ServiceDescriptor(
  name='Storage',
  full_name='capsule.Storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=154,
  serialized_end=274,
  methods=[
  _descriptor.MethodDescriptor(
    name='StoreContent',
    full_name='capsule.Storage.StoreContent',
    index=0,
    containing_service=None,
    input_type=_STOREREQUEST,
    output_type=capsule_dot_common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetContent',
    full_name='capsule.Storage.GetContent',
    index=1,
    containing_service=None,
    input_type=_STORAGEKEY,
    output_type=_STOREDDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['Storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
