# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule/worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from capsule import common_pb2 as capsule_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule/worker.proto',
  package='capsule',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63\x61psule/worker.proto\x12\x07\x63\x61psule\x1a\x14\x63\x61psule/common.proto\"\x1c\n\x0c\x43rawlRequest\x12\x0c\n\x04urls\x18\x01 \x03(\t\"?\n\rCrawlResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12!\n\x07\x63ontent\x18\x02 \x01(\x0b\x32\x10.capsule.Content2B\n\x06Worker\x12\x38\n\x05\x43rawl\x12\x15.capsule.CrawlRequest\x1a\x16.capsule.CrawlResponse0\x01\x62\x06proto3'
  ,
  dependencies=[capsule_dot_common__pb2.DESCRIPTOR,])




_CRAWLREQUEST = _descriptor.Descriptor(
  name='CrawlRequest',
  full_name='capsule.CrawlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='urls', full_name='capsule.CrawlRequest.urls', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=83,
)


_CRAWLRESPONSE = _descriptor.Descriptor(
  name='CrawlResponse',
  full_name='capsule.CrawlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='capsule.CrawlResponse.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='capsule.CrawlResponse.content', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=148,
)

_CRAWLRESPONSE.fields_by_name['content'].message_type = capsule_dot_common__pb2._CONTENT
DESCRIPTOR.message_types_by_name['CrawlRequest'] = _CRAWLREQUEST
DESCRIPTOR.message_types_by_name['CrawlResponse'] = _CRAWLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrawlRequest = _reflection.GeneratedProtocolMessageType('CrawlRequest', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLREQUEST,
  '__module__' : 'capsule.worker_pb2'
  # @@protoc_insertion_point(class_scope:capsule.CrawlRequest)
  })
_sym_db.RegisterMessage(CrawlRequest)

CrawlResponse = _reflection.GeneratedProtocolMessageType('CrawlResponse', (_message.Message,), {
  'DESCRIPTOR' : _CRAWLRESPONSE,
  '__module__' : 'capsule.worker_pb2'
  # @@protoc_insertion_point(class_scope:capsule.CrawlResponse)
  })
_sym_db.RegisterMessage(CrawlResponse)



_WORKER = _descriptor.ServiceDescriptor(
  name='Worker',
  full_name='capsule.Worker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=150,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='Crawl',
    full_name='capsule.Worker.Crawl',
    index=0,
    containing_service=None,
    input_type=_CRAWLREQUEST,
    output_type=_CRAWLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKER)

DESCRIPTOR.services_by_name['Worker'] = _WORKER

# @@protoc_insertion_point(module_scope)
